# Generated by Django 5.1.2 on 2024-10-12 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.shoppinglist')),
            ],
            options={
                'unique_together': {('shopping_list', 'product')},
            },
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='products',
            field=models.ManyToManyField(through='products.ShoppingListProduct', to='products.product'),
        ),
    ]
